spring.application.name=api-gateway
server.port=8080

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

services.identity-service.uri=${IDENTITY_SERVICE_URL:http://localhost:8081}
services.catalog-service.uri=${CATALOG_SERVICE_URL:http://localhost:8082}
services.event-service.uri=${EVENT_SERVICE_URL:http://localhost:8083}
services.customer-service.uri=${CUSTOMER_SERVICE_URL:http://localhost:8084}
services.notification-service.uri=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
