spring.application.name=notification-service
server.port=8085

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

identity-service.base-url=${IDENTITY_SERVICE_URL:http://localhost:8081}

notification.queue-name=${NOTIFICATION_QUEUE_NAME:notification.queue}

spring.data.redis.url=${REDIS_URL:redis://localhost:6380}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5673}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

fcm.credentials-json=${FCM_CREDENTIALS_JSON}
